site_name: Tiny Docs
site_description: The Knowledge base for Tiny modders
theme:
  name: material
  palette:
    primary: light green
    accent: amber
  features:
    - content.code.annotate
nav:
  - Home: index.md
  - Game Knowledge:
    - Assets Structure: game-knowledge/game-structure.md
    - Meshes Rendering: game-knowledge/meshes.md
    - Meshes :
      - Sheeps: game-knowledge/meshes/sheeps.md
    - Save System: game-knowledge/save.md
  - Modding Tools:
    - Tiny Glade Blender Add-On: modding-tools/tiny-glade-blender-add-on.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg