site_name: Tiny Docs
site_description: The Knowledge base for Tiny modders
theme:
  name: material
  palette:
    primary: light green
    accent: amber
  features:
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption