site_name: Tiny Docs
site_description: The knowledge base for Tiny Modders
theme:
  name: material
  palette:
    primary: light green
    accent: amber
  features:
    - content.code.annotate
nav:
  - Home: index.md
  - Game Knowledge:
    - Assets Structure: game-knowledge/game-structure.md
    - Meshes Rendering: game-knowledge/meshes.md
    - Objects :
      - Sheep: game-knowledge/objects/sheeps.md
      - Trees: game-knowledge/objects/trees.md
      - Terrain: game-knowledge/objects/terrain_mods/terrain.md
      - Windows: mgame-knowledge/objects/windows.md
      - Garden Brush: game-knowledge/objects/garden-brush.md
      - Ducks: game-knowledge/objects/ducks.md
      - Roofs: game-knowledge/objects/roofs.md
      - Clutter: game-knowledge/objects/clutter.md
      - Flags: game-knowledge/objects/flags.md
      - Textures:
        - Terrain Mesh: game-knowledge/objects/terrain_mods/terrain.md
        - Terrain Water Plane: game-knowledge/objects/terrain_mods/water_plane.md
        - Terrain Trees: game-knowledge/objects/terrain_mods/bg_trees.md
        - Terrain Plants: game-knowledge/objects/terrain_mods/plants.md
        - Terrain Rocks: game-knowledge/objects/terrain_mods/rocks.md
        - Terrain Textures: game-knowledge/objects/terrain_mods/textures.md
    - Savegames: game-knowledge/save.md
    - Starter Builds: game-knowledge/starterbuilds.md
  - Modding Tools:
    - How to install assets: modding-tools/installing-assets.md
    - Making your own LUT: modding-tools/lut-editing.md
    - Mesh Editing: modding-tools/mesh-edit-with-blender.md
    - Sound Editing: modding-tools/sound-editing.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
- search
- autorefs